做了一个knight run的动画
yyphan/Godie pull request #7
Opened 2023-10-22 17:39 UTC by idnduvw

虽然切出了8帧但是感觉一帧的画面太大了，要是能跟collisionshape的大小一致就好了

2023-10-23 11:19 UTC, yyphan requested changes
这个属于素材不是很友好，可以手动调一下, 我们统一用64x64的尺寸吧

![image](https://github.com/yyphan/Godie/assets/54618568/778749db-b191-4e88-9a8d-8d45424e38de)

2023-10-23 11:21 UTC, yyphan commented
直接加到Player.tscn吧，作为一个新的动画就行
不需要为这个动画新建scene

2023-11-02 12:57 UTC, idnduvw commented
又多做了几个动画，但是为什么没人merge

2023-11-02 12:58 UTC, idnduvw reviewed
懂你意思

2023-11-02 13:14 UTC, yyphan approved these changes
王美！

2023-11-02 13:15 UTC, merged